-- Create the analytics table
create table public.analytics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_type text not null,
  metadata jsonb default '{}'::jsonb
);

-- Enable Row Level Security
alter table public.analytics enable row level security;

-- Policy: Allow anon to insert (Logging events)
create policy "Allow Anonymous Insert"
  on public.analytics
  for insert
  to anon
  with check (true);

-- Policy: Allow anon to select (Viewing Dashboard)
-- In a real production app, you might restrict this to an authenticated admin user.
create policy "Allow Anonymous Select"
  on public.analytics
  for select
  to anon
  using (true);

-- realtime subscription if needed (optional)
alter publication supabase_realtime add table public.analytics;
